In [104]:
%config IPCompleter.greedy=True

In [105]:
import numpy as np
import gym
import random

In [106]:
environment = gym.make("FrozenLake-v0")

In [114]:
# Number of possible states
state_size = environment.observation_space.n

# Number of possible actions per state
action_size = environment.action_space.n

In [115]:
print(action_size)
print(state_size)

4
16


In [116]:
# A Q table for the environment
qtable = np.zeros((state_size, action_size))

In [117]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [118]:
# Total number of episodes for the training
# Episode is a fancy word for the new game (once the agent is dead, it enters a new episode)
total_episodes = 15000

# Learning rate of the agent
learning_rate = 0.8

# Max steps per episode
max_steps = 99

# Discounting rate
# The larger the gamma, the smaller the discount and the smaller the gamma, the bigger the discount
# The larger the gamma, the more agent cares about the long-term reward and less for the short-term reward
# The smaller the gamma, the less agent cares about the long-term reward and more for the short-term reward
gamma = 0.95

# Exploration parameters
# Exploration rate
epsilon = 1.0

# Exploration probability at start
max_epsilon = 1.0

# Minimum exploration probability
min_epsilon = 0.01

# Exponential decay rate for the exploration probability
decay_rate = 0.005

In [119]:
# A list for rewards
rewards = []

# Run the Q-learning algorithm forever or until the learning is stopped
for episode in range(total_episodes):
    
    # Through each loop, reset the environment
    state = environment.reset()
    
    # Step has to be reset as well, since it is in the loop and we get 'max_steps - 1' after the loop
    # Step is variable which indicates how many moves can an agent do in a single episode (in this case < 99)
    step  = 0
    
    # Set done to False meaning that the agent is not D E A D
    done = False
    
    # A number of rewards per episode
    total_rewards = 0
    
    for step in range(max_steps):

        # Choose an action a in the current world state (s)
        # First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
    
        # If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        # Else doing a random choice --> exploration
        else:
            action = environment.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = environment.step(action)
        
        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * \
                                             np.max(qtable[new_state, :]) - qtable[state, action])
        
        # Add the reward to the total_rewards
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon since agent needs less and less exploration
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4798
[[5.52094777e-02 3.43467350e-02 4.47398629e-02 4.48420220e-02]
 [2.47879899e-04 3.05324105e-04 7.56261956e-03 4.55156848e-02]
 [4.51961392e-03 4.80245654e-03 2.10561197e-02 1.94438161e-02]
 [3.24643865e-05 9.00804651e-03 7.21909970e-03 1.95368245e-02]
 [1.16362464e-01 7.43092631e-03 1.79030405e-02 2.48842330e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.42203511e-03 1.41494080e-06 8.86650659e-02 2.36084672e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.42858082e-03 2.25838681e-02 3.12320745e-03 2.32720416e-01]
 [5.49677987e-03 1.11036213e-01 1.13293840e-02 1.19622976e-02]
 [4.63373621e-01 5.42474030e-03 2.56867623e-04 6.71572781e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.67338013e-02 1.18951178e-01 4.50579497e-01 2.56012865e-02]
 [2.24852811e-01 9.05879731e-02 7.60120166e-02 9.17069052e-01]
 [0.00000000e+00 0.00000000e+00

In [120]:
# Reset the environment
environment.reset()

# 5 episodes
for episode in range(5):

    # Get the new state
    state = environment.reset()
    
    # Step 0
    step = 0
    
    # We are not dead, yet...
    done = False
    
    # Pretty-print episode number and separate with a line of dashes
    print("----------------------------------------------------")
    print("EPISODE ", episode)
    
    # Moves
    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        # Get new_state, reward, done, and info from the envioronment.step(action)
        new_state, reward, done, info = environment.step(action)
        
        # If not dead
        if done:

            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            environment.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        
        # New state
        state = new_state

# Done with the environment
# Sort of file.close
environment.close()

----------------------------------------------------
EPISODE  0
----------------------------------------------------
EPISODE  1
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 52
----------------------------------------------------
EPISODE  2
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 11
----------------------------------------------------
EPISODE  3
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 77
----------------------------------------------------
EPISODE  4
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 34
