In [19]:
%config IPCompleter.greedy=True

In [21]:
env = gym.make("Taxi-v2")
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [26]:
state_size = env.observation_space.n
print("State size is", state_size)

action_size = env.action_space.n
print("Action size is", action_size)

State size is 500
Action size is 6


In [27]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [31]:
total_episodes = 50000
max_steps = 99

learning_rate = 0.7
gamma = 0.618

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [32]:
rewards = []

for episode in range(total_episodes):
    state = environment.reset()
    step  = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)

        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = environment.action_space.sample()
        
        new_state, reward, done, info = environment.step(action)
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * \
                                             np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        state = new_state
        
        if done == True: 
            break

    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)


print(f"Score over time: {sum(rewards) / total_episodes}")
print(qtable)

Score over time: 7.65698
[[  0.           0.           0.           0.           0.
    0.        ]
 [ -1.89494435  -1.44813002  -1.89494435  -1.44813002  -0.72512948
  -10.44813002]
 [ -0.72513035   0.4447743   -0.72512948   0.4447743    2.33782249
   -8.5552257 ]
 ...
 [ -2.24827067   5.40100727  -2.12586921  -0.33540952 -10.9297398
  -10.123666  ]
 [ -1.90974427  -1.44813002  -2.48031351  -1.75471807 -11.15226737
  -10.53529006]
 [ 16.63472804  -1.27582     12.50076865  31.35602094   4.46461464
    8.93581437]]


In [33]:
environment.reset()

for episode in range(5):
    state = environment.reset()
    step = 0
    done = False

    print("----------------------------------------------------")
    print("EPISODE ", episode)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = environment.step(action)
        
        if done:
            environment.render()
            
            print("Number of steps", step)
            break
        
        state = new_state

environment.close()

----------------------------------------------------
EPISODE  0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Number of steps 13
----------------------------------------------------
EPISODE  1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Number of steps 14
----------------------------------------------------
EPISODE  2
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Number of steps 17
----------------------------------------------------
EPISODE  3
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Number of steps 10
----------------------------------------------------
EPISODE  4
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Number of steps 12
